version: '3'
services: 
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: "jhinger/fp-tone-server:1.0"
    container_name: container-fp-tone-server
    ports:
      - "3800:3800"
    